version: '2.1'
services:
  frontend:
    build:
      context: ./frontend
      args:
        - API_GATEWAY_URL=${API_GATEWAY_URL}
        - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    ports:
      - 80:80
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management
    platform: linux/arm64/v8
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  notifications-service:
    build:
      context: ./notifications-service
      dockerfile: Dockerfile
    volumes:
      - ./notifications-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - AMQP_URL=amqp://guest:guest@rabbitmq
      - NOTIFICATIONS_QUEUE=notifications
    depends_on:
      - rabbitmq

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    volumes:
      - ./movie-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=movie_db
      - DB_USER=root
      - DB_PASSWORD=root
      - AMQP_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - mysql
      - rabbitmq

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./api-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=movie_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

volumes:
  rabbitmq_data:
  mysql_data:

